// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Custom storage for Capacitor to ensure session persistence on mobile
const customStorage = {
  getItem: (key: string) => {
    if (Capacitor.isNativePlatform()) {
      return import('@capacitor/preferences').then(p => p.Preferences.get({ key }).then(r => r.value));
    }
    return localStorage.getItem(key);
  },
  setItem: (key: string, value: string) => {
    if (Capacitor.isNativePlatform()) {
      return import('@capacitor/preferences').then(p => p.Preferences.set({ key, value }));
    }
    localStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    if (Capacitor.isNativePlatform()) {
      return import('@capacitor/preferences').then(p => p.Preferences.remove({ key }));
    }
    localStorage.removeItem(key);
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage as any,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});